python main.py \
    --seed 0 \
    --gpu 1 \
    --lr 5e-5 \
    --model_name SLM \
    --language en \
    --root_path /home/tzh/ARG/data/en \
    --bert_path /home/tzh/model/bert-base-uncased \
    --data_name en-SLM \
    --data_type rationale \
    --rationale_usefulness_evaluator_weight 1.5 \
    --llm_judgment_predictor_weight 1.0 \

python main.py \
    --seed 1 \
    --gpu 1 \
    --lr 5e-5 \
    --model_name SLM \
    --language en \
    --root_path /home/tzh/ARG/data/en \
    --bert_path /home/tzh/model/bert-base-uncased \
    --data_name en-SLM \
    --data_type rationale \
    --rationale_usefulness_evaluator_weight 1.5 \
    --llm_judgment_predictor_weight 1.0 \

python main.py \
    --seed 2 \
    --gpu 1 \
    --lr 5e-5 \
    --model_name SLM \
    --language en \
    --root_path /home/tzh/ARG/data/en \
    --bert_path /home/tzh/model/bert-base-uncased \
    --data_name en-SLM \
    --data_type rationale \
    --rationale_usefulness_evaluator_weight 1.5 \
    --llm_judgment_predictor_weight 1.0 \

python main.py \
    --seed 3 \
    --gpu 1 \
    --lr 5e-5 \
    --model_name SLM \
    --language en \
    --root_path /home/tzh/ARG/data/en \
    --bert_path /home/tzh/model/bert-base-uncased \
    --data_name en-SLM \
    --data_type rationale \
    --rationale_usefulness_evaluator_weight 1.5 \
    --llm_judgment_predictor_weight 1.0 \

python main.py \
    --seed 4 \
    --gpu 1 \
    --lr 5e-5 \
    --model_name SLM \
    --language en \
    --root_path /home/tzh/ARG/data/en \
    --bert_path /home/tzh/model/bert-base-uncased \
    --data_name en-SLM \
    --data_type rationale \
    --rationale_usefulness_evaluator_weight 1.5 \
    --llm_judgment_predictor_weight 1.0 \

